export const CHAT_MESSAGE_RETENTION_MS = 2 * 60 * 60 * 1_000;
export const CHAT_BURN_AFTER_READ_SECONDS = 5 as const;
export const CHAT_EXPIRATION_SWEEP_INTERVAL_MS = 2_000;
export const CHAT_EXPIRATION_SWEEP_BATCH_SIZE = 200;
