#!/bin/bash

# iOS Helper Scripts
echo "==================================="
echo "iOS & Android Build Helper"
echo "==================================="
echo ""
echo "iOS Commands:"
echo "  1. Open Xcode:"
echo "     open ./ios/App/App.xcodeproj"
echo ""
echo "  2. Build for Simulator:"
echo "     xcodebuild -project ./ios/App/App.xcodeproj -scheme App -configuration Debug"
echo ""
echo "  3. Build for Device:"
echo "     xcodebuild -project ./ios/App/App.xcodeproj -scheme App -configuration Release"
echo ""
echo "-----------------------------------"
echo ""
echo "Android Commands:"
echo "  1. Open Android Studio:"
echo "     open -a 'Android Studio' ./android"
echo ""
echo "  2. Build Debug APK:"
echo "     cd ./android && ./gradlew assembleDebug"
echo ""
echo "  3. Build Release APK:"
echo "     cd ./android && ./gradlew assembleRelease"
echo ""
echo "  4. Build Release AAB (for Play Store):"
echo "     cd ./android && ./gradlew bundleRelease"
echo ""
echo "  5. Install on connected device/emulator:"
echo "     cd ./android && ./gradlew installDebug"
echo ""
echo "-----------------------------------"
echo ""
echo "Sync Commands:"
echo "  • Sync web assets to native:"
echo "    npx cap sync"
echo ""
echo "  • Open native IDEs:"
echo "    npx cap open ios"
echo "    npx cap open android"
echo ""
